project:
  type: book
  output-dir: docs

book:
  title: "Definição de Prioridades - Projeto Clínicas de Acesso a Direitos"
  author: "Lucas Enéas de Rezende"
  date: today
  reader-mode: true
  page-navigation: true
  page-footer:
   background: "#294661"
   center:
    - text: "Clínicas de Acesso a Direitos /"
      #href: https://www.gov.br/senappen/pt-br/servicos/sisdepen
    - text: "Diretoria de Políticas Penitenciárias - Dirpp /"
      #href: https://www.gov.br/senappen/pt-br/composicao/estrutura-organizacional
    - text: "Secretaria Nacional de Políticas Penais - Senappen /"
      #href: https://www.gov.br/senappen/pt-br
    - text: "Ministério da Justiça e Segurança Pública - MJSP"
      #href: https://www.gov.br/mj/pt-br
  cover-image: img/senappen_brasao.png
  image: img/senappen_brasao.png
  site-url: https://www.gov.br/senappen/pt-br
  sharing: [twitter, facebook, linkedin]
  search:
    location: sidebar
    type: textbox

  sidebar:
    font.family: 'Calibri'
    title: "Diretoria de Políticas Penitenciárias"
    subtitle: "Relatório de Prioridades"
    background: "#FFFFFF"
    items:
    logo: img/senappen_brasao.png
    style: docked
    alignment: left
    tools:
      - icon: git
      - href: https://www.gov.br/depen/pt-br/canais_atendimento/ouvidoria

  chapters:
    - index.qmd
    - intro.qmd
    #- summary.qmd
    #- references.qmd

bibliography: references.bib

highlight-style: pygments

format:
  html:
    embed-resources: false #COLOCA TODOS OS ARQUIVOS JUNTOS
    theme: cosmo #default #pandoc #cosmo default none
    code-link: true
    css: style.css
    code-copy: true
    #page-layout: custom
    page-layout: full
    grid:
      #sidebar-width: 400px
      body-width: 1100px
      margin-width: 200px
      #gutter-width: 1.5rem
  pdf:
    documentclass: report
    papersize: A4
    keep-tex: false
    # pdf-engine: pdflatex
    # pdf-engine-opt: -outdir=out
    toc: true
    number-sections: true
    colorlinks: true
    #fontfamily: Calibri
  # epub:
  #   cover-image: images/senappen_brasao.png

knitr:
  opts_chunk:
    fig.align: "center"
    message: false
    echo: false
    results: true
    dpi: 300
    warning: false
    out-width: NULL
    fig.responsive: true
    comment: false

lang: pt
csl: abnt.csl

editor: visual

